# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "https://jcnauta.github.io/lean-site-template/"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be the English site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "EA Groningen"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Groningen"
  strapline = "Helping you do good better"

  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism Groningen"
  orgLocations = "Groningen"
  contactEmail = "mail@eagroningen.com"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.

  effectiveAltruism = "Effective Altruism"
  principles = "Principles"
  learnMore = "Learn More"

  eaGroningen = "EA Groningen"
  goals = "Goals"
  community = "Community"
  whatDoWeDo = "What do we do?"
  organization = "Organization"

  getInvolved = "Get Involved"
  individuals = "Individuals"
  organizations = "Organizations"

  contact = "Contact"

  [Languages.en.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  #firstButtonText = "Join us on Facebook"
  #firstButtonLink = "https://www.facebook.com/groups/EffectiefAltruismeGroningen/"
  #secondButtonText = "Second Button Text"
  #secondButtonLink = ""
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/groups/EffectiefAltruismeGroningen/"
  #twitterUrl = ""
  meetupUrl = "https://www.meetup.com/Effective-Altruism-Groningen/"