# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "https://jcnauta.github.io/lean-site-template/"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be the English site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.

  [params]

  [Languages]
  [Languages.en]
    title = "EA Groningen"
    weight = 1
    languageCode = "en"
  [Languages.nl]
    title = "EA Groningen"
    weight = 2
    languageCode = "nl"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Groningen"
  strapline = "Helping you do good better"
  [Languages.nl.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effectief Altruisme Groningen"
  strapline = "De wereld beter verbeteren"

  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism Groningen"
  orgLocations = "Groningen"
  contactEmail = "mail@eagroningen.com"

  [Languages.nl.groupinfo]
  legalOrgName = "Effectief Altruisme Groningen"
  orgLocations = "Groningen"
  contactEmail = "mail@eagroningen.com"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  effectiveAltruism = "Effective Altruism"
  principles = "Principles"
  learnMore = "Learn More"

  eaGroningen = "EA Groningen"
  whoAreWe = "Who are we?"
  whatDoWeDo = "What do we do?"
  organization = "Organization"

  getInvolved = "Get Involved"
  contact = "Contact"
  faq = "FAQ"

  [Languages.nl.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  effectiveAltruism = "Effectief Altruisme"
  principles = "Principes"
  learnMore = "Meer Weten"

  eaGroningen = "EA Groningen"
  whoAreWe = "Wie zijn wij?"
  whatDoWeDo = "Wat doen we?"
  organization = "Organisatie"

  getInvolved = "Doe mee"
  contact = "Contact"
  faq = "FAQ"  

  [Languages.en.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"
  [Languages.nl.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Neem contact met ons op"
  aboutEAPageHeader = "Wat is Effectief Altruisme?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"
  [Languages.nl.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Wie zijn wij?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Send us a message!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"
  [Languages.nl.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Stuur ons een bericht!"
  senderName = "Je naam (vereist)"
  senderEmail = "Je emailadres (vereist)"
  emailSubject = "Onderwerp"
  emailMessage = "Bericht"
  send = "Verstuur"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/groups/EffectiefAltruismeGroningen/"
  #twitterUrl = ""
  meetupUrl = "https://www.meetup.com/Effective-Altruism-Groningen/"
  [Languages.nl.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/groups/EffectiefAltruismeGroningen/"
  #twitterUrl = ""
  meetupUrl = "https://www.meetup.com/Effective-Altruism-Groningen/"