baseURL = "https://raw.githubusercontent.com/jcnauta/lean-site-template/master/static/img/city-banner.jpg"
languageCode = "en-us"
title = "EA Groningen"
theme = "local-ea-template"

[params]
  fullTitle = "Effective Altruism Groningen"
  strapline = "Helping you do good better"
  firstButtonText = "Join us on Facebook"
  firstButtonLink = "https://www.facebook.com/groups/EffectiefAltruismeGroningen/"
